version: '3'

services:

  nginx:
    image: nginx:latest
    ports:
      - 6666:80
    volumes:
      - ./app:/app
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - frontend
      - backend

  php:
    image: php:7-fpm
    volumes:
      - ./app:/app
    networks:
      - backend

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - 'mysql:db'
    ports:
      - 6001:80
    networks:
      - backend

networks:
  frontend:
  backend: