version: '3'

services:

  nginx:
    build:
      context: ./build/nginx
    ports:
      - 6666:80
    volumes:
      - ./app:/app
    networks:
      - frontend
      - backend

  php:
    build: 
      context: ./build/php
    volumes:
      - ./app:/app
    networks:
      - backend

  mysql:
    build:
      context: ./build/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - ./database:/var/lib/mysql
    networks:
      - backend

  phpmyadmin:
    build: 
      context: ./build/phpmyadmin
    links:
      - 'mysql:db'
    ports:
      - 6001:80
    networks:
      - backend

networks:
  frontend:
  backend: